classmates = ['Michael', 'Bob', 'Tracy']
print(classmates, len(classmates))
print(classmates[0], classmates[2], classmates[-1])
classmates.append('Adam')
print(classmates)
print(classmates.append('changwanli'))
classmates.insert(1, 'Jack')
print(classmates)
classmates.pop()
print(classmates)
classmates.pop(1)
print(classmates)
classmates.append([1,2,3,4])
print(classmates)
t = (1,2)
print(t)
t = (1,)
print(t)
t = (1,2,3,['x', 'y'])
print(t)
t[3][0] = 'z'
print(t)
t = z = 'az'
print(t)
